export const Works = [
  {
    Type: "Front",
    Name: "Local Sticky Notes",
    Image: 'src="./media/Image/sticky.jpg"',
    Description: "lorem",
    Tool: ["Javascript", "CSS"],
    Link: ["", ""],
  },
  {
    Type: "Front",
    Name: "IceScreen Responsive CSS Library",
    Image: "",
    Description: "",
    Tool: ["Javascript", "CSS"],
    Link: ["", ""],
  },
  {
    Type: "",
    Name: "React Hooks Example",
    Image: 'src="./media/Image/sticky.jpg"',
    Description: "",
    Tool: ["React", "CSS"],
    Link: ["", ""],
  },
  {
    Type: "",
    Name: "Wedding Invitations",
    Image: "",
    Description: "",
    Tool: ["Javascript", "CSS"],
    Link: ["", ""],
  },
  {
    Type: "FullStack",
    Name: "South Park REST-API",
    Image: 'src="./media/Image/south-park-4.webp"',
    Description: "",
    Tool: ["Javascript", "CSS", "Node JS", "Express"],
    Link: ["", ""],
  },
  {
    Type: "",
    Name: "Lonney Tunes RESTAPI",
    Image: 'src="./media/Image/looeny-tunes.jpg"',
    Description: "",
    Tool: ["Javascript", "CSS", "Node JS", "Express"],
    Link: ["", ""],
  },
  {
    Type: "",
    Name: "Restaurant Menu & Daily foods",
    Image: "",
    Description: "",
    Tool: ["React", "CSS", "Node JS", "Express"],
    Link: ["", ""],
  },
  {
    Type: "CFirmware",
    Name: "Stringify Library for C Like Js",
    Image: "",
    Description: "",
    Tool: ["C"],
    Link: ["", ""],
  },
  {
    Type: "Front-End",
    Name: "Criptography Basic Library",
    Image: 'src="./media/Image/cripto.jpg"',
    Description: "",
    Tool: ["C"],
    Link: ["", ""],
  },
  {
    Type: "Embedded",
    Name: "Cycling Safety System",
    Image: 'src="./media/Image/safety.jpg"',
    Description: "",
    Tool: ["C", "Microchip"],
    Link: ["", ""],
  },
  {
    Type: "",
    Name: "Public Transport Security System with AI",
    Image: 'src="./media/Image/cv.png"',
    Description: "",
    Tool: ["C", "Python", "Espressif"],
    Link: ["", ""],
  },
];
